liip_imagine:

    driver: "imagick"

    filter_sets:

        square_thumbnail_medium:

            filters:

                thumbnail: { size: [300, 300], mode: outbound }

        square_thumbnail_small:
            filters:

                thumbnail: { size: [200, 200], mode: outbound }